options {
    forwarders {
        1.1.1.1;
        8.8.8.8;
    };
    allow-query {
        10.10.0.0/16;
    };
};

zone "home.underscore.space" IN {
    type master;
    file "/etc/bind/zones/home.underscore.space";
};

zone "home.messy.cloud" IN {
    type master;
    file "/etc/bind/zones/home.messy.cloud";
};
