options {
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    allow-query {
        10.10.0.0/16;
    };
};

zone "home.messy.cloud" IN {
    type master;
    file "/etc/bind/zones/home.messy.cloud";
};
