services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /opt/docker/mqtt:/mosquitto/config:ro
networks: {}