services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    tmpfs:
      - /tmp
    volumes:
      - /opt/docker/caddy:/etc/caddy:ro
      - /var/www:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      EMAIL: ${EMAIL}
      DOMAIN: ${DOMAIN}
      NETLIFY_TOKEN: ${NETLIFY_TOKEN}
      OLD_DOMAIN: ${OLD_DOMAIN}
    networks:
      web:
        aliases:
          - caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  web:
    external: true
volumes:
  caddy_data: null
  caddy_config: null
