services:
  duckdns:
    container_name: duckdns
    restart: unless-stopped
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    dns:
      - 1.1.1.1
    tmpfs:
      - /run:exec
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBDOMAINS=${DUCKDNS_DOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
  dns:
    container_name: dns
    restart: unless-stopped
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/London
    ports:
      - 10.10.1.20:53:53/tcp
      - 10.10.1.20:53:53/udp
    volumes:
      - /opt/docker/dns:/etc/bind
      - dns-records:/var/lib/bind
      - dns-cache:/var/cache/bind
volumes:
  dns-cache: null
  dns-records: null
networks: {}
